name: Validate Branch Name

on:
  pull_request:
    branches:
      - main

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Check branch name
        run: |
          echo "Validating branch name..."
          BRANCH_NAME=$(echo "${{ github.head_ref }}")
          echo "Branch name is $BRANCH_NAME"
          if [[ ! $BRANCH_NAME =~ ^bug/ ]]; then
            echo "Branch name does not follow the convention. It must start with 'bug/'."
            exit 1
          fi
